config/routes.rb
Rails.application.routes.draw do
  resources :users, :sessions

  resources :books do

   collection do
     post 'search', to: 'books#search'
   end
   end

  root 'sessions#welcome'
  get 'signup', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/audio.rb
class Audio < ActiveRecord::Base
  attr_reader :state
  def start
    @state = 'begin'
  end

  def stop
    @state = 'end'
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  mount_uploader :poster, PosterUploader
  validates :author, :title, presence: true

  belongs_to :user

  scope :for_user, ->(user) { where(user: user) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books

  has_secure_password

  validates :name, :email, :role, presence: true


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false}

  validates :password, length: { minimum: 6}

  def admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authorize
    redirect_to signin_path, alert: "Not authorized" if current_user.nil?
  end

  def authenticate
    if current_user
      return true
    else
      flash[:warning] = 'You must be signed in.'
      redirect_to root_path
    end
  end

  def signed_in
    current_user == 'true'
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:new, :index, :destroy]


  def search
    @books = Book.for_user(current_user).where('title like ?', "%#{params[:search_query]}").order(params[:sort]).page(params[:page]).per(5)
    render :template => 'books/index'
  end

  # GET /books
  # GET /books.json
  def index
   @books = Book.for_user(current_user).order(params[:sort]).page(params[:page]).per(5)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.where(user: current_user).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :poster, :user_id)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authenticate, only: [:welcome, :signin, :signup]

  def welcome
  end

  def signup
  user = User.new(name: params[:name],
                  email: params[:email],
                  password: params[:password],
                  password_confirmation: params[:password_confirmation])

    if user.save
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully signed up.'
    else
      flash[:error] = "We were unable to sign you up. #{user.errors.full_messages.join('. ')}."
    end

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in"
      redirect_to books_path
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end


  def signout
    session[:user_id] = nil
    flash[:warning] = 'You have signed out!'
    redirect_to root_path
  end
 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:welcome,  :signin, :signup]

  def welcome
  end

  def signup
  user = User.new(name: params[:name],
                  email: params[:email],
                  password: params[:password],
                  password_confirmation: params[:password_confirmation])

    if user.save
      session[:user_id] = user.id
      flash[:notice] = 'You have successfully signed up.'
    else
      flash[:error] = "We were unable to sign you up. #{user.errors.full_messages.join('. ')}."
    end

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in"
      redirect_to books_path
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end


  def destroy
    session[:user_id] = nil
    flash[:warning] = 'You have signed out!'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, only: [:show, :index, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to books_path, notice: 'Thank you for signing up.' }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  helper_method :require_admin

  def require_admin
    if current_user && !current_user.admin?
      flash[:error] = "Not Authorized"
      redirect_to root_url # halts request cycle
    end
  else
  end
    # Use callbacks to share common setup or constraints between actions.

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :role)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for(@book, :html => {:multipart => true}) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="small-4 columns">
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :user_id %>
    <%= f.select :user_id, User.all.collect {|user| [user.name, user.id]} %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.file_field :poster %>
  <div class="actions">
<button class="small success button">Submit</button>
  </div>
</div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="container">
  <%= form_tag search_books_path, class: 'form' do %>
      <%= text_field_tag "search_query", nil, placeholder: 'Search text' %>
      <%= submit_tag "Search", class: 'radius button tiny' %>
  <% end %>
</div>

<div>
<h3>Listing books</h3>

<%= paginate @books %>
<table>
  <thead>
    <tr>
      <th><%=  link_to "Title", sort: "title" %></th>
      <th><%=  link_to "Author", sort: "author"%></th>
      <th><%= link_to "User", sort: "user" %></th>
      <th>Cover</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.user.name if book.user%></td>
        <td><%= image_tag book.poster_url(:thumb).to_s %></td>
        <td><i class="fi-plus large""></i><%= link_to 'Show', book %></td>
        <td><i class="fi-pencil large"></i><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><i class="fi-trash large"></i><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>
<div>
  <%= image_tag @book.poster_url.to_s %>

</div>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
  <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>


<li class="name"><%= link_to 'Books', books_path %></li>
<li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
<% if @current_user && @current_user.role == 'admin' %>
<li class="name"><%= link_to 'Users', users_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
	<% else %>
<% end %>

app/views/layouts/_notices.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
          <%= content_tag :div, msg %>
          <a href="#" class="close">&times;</a>
        </div>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="plugins/foundation-glyphicons/stylesheets/foundation-glyphicons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Book Tracking" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Book Tracking" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <header>
      <%= render 'layouts/navigation' %>
      <div>
        <% if current_user %>
            Hello, <%= current_user.name %>.
            <%= link_to "Sign Out", session_path("current"), method: "delete" %>
        <% else %>
            <h4> Welcome!</h4>
        <% end %>
      </div>
    </header>
    <main role="main">
       <%= render 'layouts/notices' %>
    <%= yield %>
    </main>
  </body>
</html>

app/views/users/_form.html.erb
<div class="form">
  <%= simple_form_for @user do |form| %>
      <%= form.input :name, label: false, placeholder: 'Name', autofocus: true %>
      <%= form.input :email, label: false, placeholder: 'Email Address' %>
      <%= form.input :password, label: false, placeholder: 'Password' %>
      <%= form.input :password_confirmation, label: false, placeholder: 'Password Confirmation' %>
      <%= form.button :submit, 'Sign up', class: 'radius button [secondary success alert];'  %>
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h2>Please sign up</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Book Tracker</h1>
<h3> Keep track of all the books you've bought while traveling</h3>


<%= form_tag signin_path do %>
    <%=






<%= link_to 'New Book', new_book_path %>

<%= link_to 'View Selections', books_path %>